<?php
/**
 * Copy taxonomy term to another VID and/or parent. Trigger copy of children
 */
function _taxonomy_copy_copy_term($oldtid, $newvid, $newparent, $newname) {
  $new_term = taxonomy_term_load($oldtid);
  if (isset($new_term->tid)) {
    unset($new_term->tid);
  };
  if (isset($new_term->vocabulary_machine_name)) {
    unset($new_term->vocabulary_machine_name);
  };
  if (isset($new_term->original)) {
    unset($new_term->original);
  };
  $new_term->name = $newname;
  $new_term->parent = $newparent;
  $new_term->vid = $newvid;
  $new_term->weight = '0';
  $status = taxonomy_term_save($new_term);
  if ($status == '1') { 
    $old_term = taxonomy_term_load($oldtid);
    $children = taxonomy_get_tree($old_term->vid, $oldtid, '1');
    foreach ($children as $child) {
      _taxonomy_copy_copy_term_children($child->tid, $newvid, $new_term->tid);
    }
    return $new_term;
  }
  else {
   drupal_set_message(t('Term copy failed with status: %status', array('%status' => $status))); 
   // break;
  }
}

/**
 * Copy a child term to the new VID/parent.
 * This is the same as _taxonomy_copy_copy_term(), but only returns status
 */
function _taxonomy_copy_copy_term_children($oldtid, $newvid, $newparent) {
  $new_term = taxonomy_term_load($oldtid);
  if (isset($new_term->tid)) {
    unset($new_term->tid);
  };
  if (isset($new_term->vocabulary_machine_name)) {
    unset($new_term->vocabulary_machine_name);
  };
  if (isset($new_term->original)) {
    unset($new_term->original);
  };
  $new_term->parent = $newparent;
  $new_term->vid = $newvid;
  $new_term->weight = '0';
  $status = taxonomy_term_save($new_term);
  if ($status == '1') { 
    $old_term = taxonomy_term_load($oldtid);
    $children = taxonomy_get_tree($old_term->vid, $oldtid, '1');
    foreach ($children as $child) {
      _taxonomy_copy_copy_term_children($child->tid, $newvid, $new_term->tid);
    }
    return TRUE;
  }
  else {
   drupal_set_message(t('Term copy failed with status: %status', array('%status' => $status))); 
   return FALSE;
   // break;
  }
}

/**
 * Just in case: function to copy a vocabulary to a new term parent.
 * Vestigial, but may as well keep it around.
 */

function _taxonomy_copy_copy_vocab($oldvid, $newvid, $newparent) {
  $top_tids = taxonomy_get_tree($oldvid, '0', '1');
  foreach ($top_tids as $tid) {
    // _taxonomy_copy_copy_term($tid->tid, $newvid, $newparent);
  }
}

/**
 * Rules Action wrapper: Copy taxonomy term
 */
function taxonomy_copy_copy_term($oldterm, $newvocab, $newparentobj, $newname) {
  $oldtid = $oldterm->tid;
  $newvid = $newvocab->vid;
  $newparent = $newparentobj->tid;
  $created_term = _taxonomy_copy_copy_term($oldtid, $newvid, $newparent, $newname);
  return array('created_term' => $created_term);
}
