<?php

//@file tweaks behavior on call and event creation forms for an easier workflow.

/**
 * Implements hook_form_alter()
 */
function schedulearts_eventwiz_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
  case 'call_node_form':
    if (isset($form['actions']['addanother'])) {
      $form['actions']['addanother']['#submit'][] = 'schedulearts_eventwiz_addanother_submit_handler';
    }
    break;
  case 'event_node_form':
    $form['actions']['addcall'] = array(
      '#type' => 'submit',
      '#value' => 'Save and add Calls',
      '#weight' => -41,
      '#submit' => array('node_form_submit', 'schedulearts_eventwiz_addcall_form_submit'),
    );
    break;
  }
}

/**
 * Submit handler for addanother submits on Call forms. Retains post information
 */
function schedulearts_eventwiz_addanother_submit_handler($form, &$form_state) {
  if (isset($form['actions']['addanother'])) {
    $form_state['redirect'] = array($form_state['redirect']);
    $form_state['redirect'][]['query']['edit']['field_call_parent_event']['und'] = $form_state['values']['field_call_parent_event']['und']['0']['target_id'];
  }
}
       
/**
 * Submit handler for addcall submits on Event forms. Redirects user to add a relevant call.
 */
function schedulearts_eventwiz_addcall_form_submit($form, &$form_state) {
  if (isset($form['actions']['addcall'])) {
    $form_state['redirect'] = array('node/add/call');
    $form_state['redirect'][]['query']['edit']['field_call_parent_event']['und'] = $form_state['values']['nid'];
  }
}

/**
 * Implements hook_block_info()
 */
function schedulearts_eventwiz_block_info() {
  $blocks['add_calls'] = array(
    'info' => t('Event > Add Calls button'),
    'status' => TRUE,
    'region' => 'content',
    'weight' => -25,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'events/*',
  );
  return $blocks;
}

/**
 * Implements hook_block_view()
 */
function schedulearts_eventwiz_block_view($delta = '') {
  switch ($delta) {
  case 'add_calls':
    $block['content'] = schedulearts_eventwiz_block_contents($delta);
    return $block;
    break;
  }
}

/**
 * The Add Calls button block, to be positioned on Events
 */
function schedulearts_eventwiz_block_contents($delta) {
  switch ($delta) {
  case 'add_calls':
    if (user_access('call: create new content')) {
      $current_nid = (arg(0) == 'node' && is_numeric(arg(1)) ? arg(1) : NULL);
      return (drupal_get_form('schedulearts_eventwiz_block_addcall_form', $current_nid));
    }
  }
}

/**
 * Defines the form for Add Calls button block
 */
function schedulearts_eventwiz_block_addcall_form($form_id, &$form_state, $current_nid) {
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Add Calls',
  );
  if (!empty($form_state['build_info']['args']['0'])) {
    $current_nid = $form_state['build_info']['args']['0'];
    $form['#action'] = url('node/add/call', array('query' => array('edit' => array('field_call_parent_event' => array('und' => $current_nid)))));
  }
  return $form;
}

