<?php
/**
 * @file
 * Gather user‘s personal schedule and send in an email.
 */

/**
 * Implements hook_menu().
 */
function schedulearts_user_schedule_menu() {
  $items['schedule/%user/%node'] = array(
    'title' => 'Personal Schedule Email Format',
    'page callback' => 'schedulearts_user_schedule_render',
    'page arguments' => array(1, 2),
    'access arguments' => array('access content'),
  );
  return $items;
}
/**
 * Render the calls in a dete range of a given schedule for a user.
 *
 * @param stdClass $account
 * A standard user object the schedule is displayed for.
 * @param stdClass $node
 * The node that defines the range and groups of the schedule. 
 */
function schedulearts_user_schedule_render($account, $node) {
  if ($node->type !== 'schedule') {
    return '';
  }
  $schedule_date = reset(field_get_items('node',$node,'field_sched_date'));
  var_dump($schedule_date); die();
}