<?php

/**
 * @file:
 * Gives certain configurable taxonomy terms their own delete
 * permission.
 */

/*
 * Implements hook_form_ID_alter()
 * Tweaks to the Event Type form.
 */
function schedulearts_undeletables_form_taxonomy_form_term_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'taxonomy_form_term') {
    // preserve "Reserved" TIDs from deletion
    $form['actions']['delete']['#access'] = schedulearts_undeletables_reserved_term_access($form['tid']['#value'], $form['actions']['delete']['#access']);
  }
}

/**
 * Implements hook_views_api().
 */
function schedulearts_undeletables_views_api() {
  return array(
    'api' => 3,
    'template path' => drupal_get_path('module', 'schedulearts_undeletables'),
  );
}

/**
 * Custom access callback for reserved TIDs
 */
function schedulearts_undeletables_reserved_term_access($tid, $access=NULL) {
  $reservedtids = variable_get('schedulearts_undeletables_reserved_eventtypes', array());
  // Sometimes TID is passed as a term object. We just want TID
  if (is_object($tid)) {
    $tid_number = $tid->tid;
  }
  else {
    $tid_number = $tid;
  }
  // Check our reserved TIDs
  if (in_array($tid_number, $reservedtids)) {
    return FALSE;
  }
  // If we haven't already denied access before or during this function, check for taxonomy_edit access
  if ($access != FALSE) {
    return taxonomy_term_edit_access($tid);;
  }
  return TRUE;
}

/**
 * Custom access callback for deleting reserved TIDs
 * (requires our custom taxonomy_delete_link module)
 */
function schedulearts_undeletables_reserved_term_delete_access($tid) {
  $access = taxonomy_delete_link_access($tid);
  return schedulearts_undeletables_reserved_term_access($tid, $access);
}

/**
 * Implements hook_permission().
 */
function schedulearts_undeletables_permission() {
  return array(
    'configure schedulearts_undeletables admin settings' => array(
      'title' => 'Configure schedulearts_undeletables admin settings',
    ),
  );
}

/**
 * Implements hook_menu().
 */
function schedulearts_undeletables_menu() {
  $items = array();

  $items['admin/config/schedulearts_undeletables'] = array(
    'title' => t('schedulearts_undeletables Custom settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('schedulearts_undeletables_admin_settings_form'),
    'access arguments' => array('configure schedulearts_undeletables admin settings'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'schedulearts_undeletables.admin.inc',
  );

  return $items;
}

/*
 * Implements hook_menu_alter()
 * Improving access callbacks for Taxonomy vocabulary menu items. So "edit" is the only permission you need
 */
function schedulearts_undeletables_menu_alter(&$items) {
  // Taxonomy edit and delete term forms
  $items['taxonomy/term/%taxonomy_term/edit']['access callback'] = 'schedulearts_undeletables_reserved_term_access';
  $items['taxonomy/term/%taxonomy_term/edit']['access arguments'] = array(2);

  // Delete link - from taxonomy_delete_link module
  $items['taxonomy/term/%taxonomy_term/delete']['access callback'] = 'schedulearts_undeletables_reserved_term_delete_access';
  $items['taxonomy/term/%taxonomy_term/delete']['access arguments'] = array(2);
}

/**
 * Implements hook_taxonomy_term_delete().
 */
function schedulearts_undeletables_taxonomy_term_delete($term) {
  drupal_goto('content/event-types');
}

/**
 * Implements hook_taxonomy_term_update().
 */
function schedulearts_undeletables_taxonomy_term_update($term) {
  drupal_goto('content/event-types');
}
