<?php

/**
 * Implements hook_menu().
 */
function schedulearts_clone_events_menu() {
  $items['schedulearts_clone/clone/%'] = array(
    'title' => 'My blog',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('schedulearts_clone_events_clone_method_selector_form', 2),
    'access callback' => 'user_access',
    'access arguments' => array('clone event'),
    'file' => 'schedulearts_clone_events.pages.inc',
  );
  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function schedulearts_clone_events_menu_alter(&$items) {
  $items['node/%node/clone']['type'] = MENU_CALLBACK;
  $items['node/%node/clone']['page callback'] = 'schedulearts_clone_events_node_check';
}

/**
 *  Menu callback: prompt the user to confirm the operation
 */
function schedulearts_clone_events_node_check($node) {
  $method = variable_get('clone_method', 'prepopulate');

  module_load_include('inc', 'clone', 'clone.pages');

  $ajax = (isset($_SERVER['HTTP_X_REQUESTED_WITH'])
    && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) === 'xmlhttprequest');

  switch ($method) {
    case 'save-edit':
      if (variable_get('clone_nodes_without_confirm', FALSE)) {
        $new_nid = clone_node_save($node->nid);
        if ($ajax) {
          ajax_deliver(_ctools_automodal_redirect('node/'. $new_nid .'/edit', $options));
        }
        drupal_goto('node/'. $new_nid .'/edit');
      }
      else {
        if ($ajax) {
          $form_state = array(
            'ajax' => TRUE,
            'build_info' => array('args' => array($node)),
          );
          // @todo? $form = drupal_rebuild_form($form_id, $form_state);
          $commands = ctools_modal_form_wrapper('clone_node_confirm', $form_state);
          ajax_deliver($commands);
        }
        return drupal_get_form('clone_node_confirm', $node);
      }
      break;
    case 'prepopulate':
    default:
        if ($ajax){
          schedulearts_clone_events_node_prepopulate_ajax($node);
        }
        return clone_node_prepopulate($node);
      break;
  }
}

/**
 *  Clones a node - prepopulate a node editing form
 */
function schedulearts_clone_events_node_prepopulate_ajax($original_node) {
  if (isset($original_node->nid)) {
    global $user;

    if (clone_is_permitted($original_node->type)) {
      $node = clone $original_node;

      $node->nid = NULL;
      $node->vid = NULL;
      $node->tnid = NULL;
      // Anyonmymous users don't have a name.
      // @see: drupal_anonymous_user().
      $node->name = isset($user->name) ? $user->name : NULL;
      $node->uid = $user->uid;
      $node->created = NULL;
      $node->menu = clone_node_clone_menu_link($original_node);
      if (isset($node->book['mlid'])) {
        $node->book['mlid'] = NULL;
        $node->book['has_children'] = 0;
      }
      $node->path = NULL;
      $node->files = array();
      $node->title = t('Clone of !title', array('!title' => $node->title));
      // Add an extra property as a flag.
      $node->clone_from_original_nid = $original_node->nid;
      drupal_set_title($node->title);

      if (variable_get('clone_reset_'. $node->type, FALSE)) {
        $node_options = variable_get('node_options_'. $node->type, array('status', 'promote'));
        // Fill in the default values.
        foreach (array('status', 'moderate', 'promote', 'sticky', 'revision') as $key) {
          // Cast to int since that's how they come out of the DB.
          $node->$key = (int) in_array($key, $node_options);
        }
      }
      // Let other modules do special fixing up.
      $context = array('method' => 'prepopulate', 'original_node' => $original_node);
      drupal_alter('clone_node', $node, $context);
      // Make sure the file defining the node form is loaded.
      form_load_include($form_state, 'inc', 'node', 'node.pages');
      return ctools_automodal_node_edit($node, TRUE);
    }
  }
}

/**
 * Implements hook_block_info().
 */
function schedulearts_clone_events_block_info() {
  // Our "Add Calls" button
  $blocks['clone_event'] = array(
    'info' => t('Event > Clone Event'),
    'status' => TRUE,
    'region' => 'content',
    'weight' => -24,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'events/*',
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['delete_event'] = array(
    'info' => t('Event > Delete Event'),
    'status' => TRUE,
    'region' => 'content',
    'weight' => -26,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'events/*',
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function schedulearts_clone_events_block_view($delta) {
  switch ($delta) {
  case 'clone_event':
    if (user_access('clone event') && $node = menu_get_object('node')) {
      $block['content'] = l(t('Clone event'), "schedulearts_clone/clone/{$node->nid}", array(
        'attributes' => array('class' => array('button')),
      ));
    }
  break;
  case 'delete_event':
    if (($node = menu_get_object('node')) && node_access('delete', $node)) {
      $block['content'] = l(t('Delete event'), "node/{$node->nid}/delete", array(
        'attributes' => array('class' => array('button')),
      ));
    }
    break;
  }
  return $block;
}

/**
 * Implements hook_permission().
 *
 */
function schedulearts_clone_events_permission() {
  return array(
    'clone event' => array(
      'title' => t('Use schedulearts event clone functionality'),
      'description' => t('Clone events using schedulart\'s UI.'),
    ),
  );
}

/**
 * Create clones of an event in the specified dates.
 *
 * @param int $nid ID of the original node.
 * @param string $dates Dates of the new events.
 */
function schedulearts_clone_events_mass_clone_events($nid, $dates) {
  $no = 1;
  $node = node_load($nid);
  foreach ($dates as $date) {
    schedulearts_clone_events_clone_event($node, $date, $no);
    $no++;
  }
}

/**
 * Creates a clone of an event.
 *
 * @param int $nid Id of the original node
 * @param string $date Start date of the new event.
 * @param int/string $no Postfix of the title.
 * @return type
 * @internal We can't use clone_node_save() because it does not change the event
 *   date, and clone_node_alter does not have information about the list of the
 *   new dates.
 */
function schedulearts_clone_events_clone_event($original_node, $date, $no = '') {
  module_load_include('inc', 'clone', 'clone.pages');
  if (isset($original_node->nid) && user_access('clone event')) {
    $node = clone $original_node;
    $node->nid = NULL;
    $node->vid = NULL;
    $node->tnid = NULL;

    $node->name = isset($user->name) ? $user->name : NULL;
    $node->uid = $GLOBALS['user']->uid;
    $node->created = NULL;
    $node->menu = clone_node_clone_menu_link($original_node);
    $node->path = NULL;
    $node->files = array();
    $node->title = $node->title;

    $node->field_event_date[LANGUAGE_NONE][0]['value2'] = _schedulearts_clone_events_calculate_end_date(
      $node->field_event_date[LANGUAGE_NONE][0]['value'],
      $node->field_event_date[LANGUAGE_NONE][0]['value2'],
      $date
    );

    $node->field_event_date[LANGUAGE_NONE][0]['value'] = $date;
    node_save($node);
  }
  if (!$node->nid) {
    drupal_set_message(t('Could not clone !title', array('!title' => $node->title)), 'error');
  }
  else {
    drupal_set_message(t('!title has been scheduled for !start_date', array(
      '!title' => $node->title,
      '!start_date' => $date)), 'status');
  }
  return $node->nid;
}

/**
 * Calculates the end of an event.
 *
 * @param string $original_start_date Start date of the original event.
 * @param string $original_end_date End date of the original event.
 * @param string $new_start_date Start date of the new event.
 * @return string End date of the new event.
 * @todo Make it use the DATE API to prevent any potential issues with timezones.
 */
function _schedulearts_clone_events_calculate_end_date($original_start_date, $original_end_date, $new_start_date) {
  return date('Y-m-d H:i:s', strtotime($new_start_date) + (strtotime($original_end_date) - strtotime($original_start_date)));
}
