<?php

function schedulearts_date_refresh_views_pre_view(&$view, &$display_id, &$args) {
  if (preg_match('/.*calendar.*/i', $display_id) && isset($_REQUEST['date'])) {
    $date_str = $_REQUEST['date'];
    $ymd = explode('-', $date_str);
    if (count($ymd) < 3 || !is_numeric($ymd[2]) || !is_numeric($ymd[1]) || !is_numeric($ymd[0])) {
      return;
    }
    $year = $ymd[0];
    $month = intval($ymd[1]);
    $day = intval($ymd[2]);
    $js = '(function($){$(document).ready(function(){$(".fullcalendar").fullCalendar("gotoDate", "'. $year . '", ' . ($month - 1) . ', ' . $day . ');})})(jQuery);';
    drupal_add_js($js, array('type' => 'inline', 'scope' => 'footer'));
  }
}

function schedulearts_date_refresh_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'event' && $view_mode == 'full') {
    if (isset($node->field_event_date) && isset($node->field_event_date['und']) && isset($node->field_event_date['und'][0])) {
      $date_parts = explode(' ', $node->field_event_date['und'][0]['value']);
      $date = $date_parts[0];
    } else {
      return;
    }
    $path = drupal_get_path('module', 'schedulearts_date_refresh') . '/schedulearts_date_refresh.js';
    drupal_add_js($path, array('type' => 'file', 'scope' => 'footer'));
    // This is about as ugly as the overlay module.
    $js = '(function($){$(window.top.document).ready(function(){'.
  '$(document).bind(\'drupalOverlayBeforeClose\', function() {'.
  '_url = window.top.location.href;'.
  "param = 'date=$date';".
  '_url = (_url.indexOf("?") !== -1 ?'.
  '_url.split("?")[0]+"?"+param+"&"+_url.split("?")[1] :'.
  '(_url.indexOf("#") !== -1 ?'.
  '_url.split("#")[0]+"?"+param+"#"+ _url.split("#")[1] : _url+\'?\'+param));'.
  'window.top.location.href = _url;})})(jQuery);';
    drupal_add_js($js, array('type' => 'inline', 'scope' => 'footer'));
  }
}