<?php

function schedulearts_date_refresh_views_pre_view(&$view, &$display_id, &$args) {
  drupal_set_message(1);
  if (preg_match('/.*fullcalendar.*/i', $display_id) && isset($_REQUEST['date'])) {
    drupal_set_message(2);
    $date_str = $_REQUEST['date'];
    drupal_set_message(3);
    $ymd = explode('-', $date_str);
    drupal_set_message(4);
    if (count($ymd < 3) || !is_numeric($ymd[2]) || !is_numeric($ymd[1]) || !is_numeric($ymd[0])) {
      drupal_set_message(5);
      dpm($ymd);
      return;
    }
    $year = $ymd[0];
    $month = intval($ymd[1]);
    $day = intval($ymd[2]);
    $js = '(function($){$(document).ready(function(){$(".fullcalendar").fullCalendar("gotoDate", "'. $year . '", ' . $month - 1 . ', ' . $day - 1 . ');})})(jQuery);';
    drupal_add_js($js, array('type' => 'inline', 'scope' => 'footer'));
  }
}
